app/main/forms.py
from ast import Sub
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired, ValidationError
from flask_login import current_user

class CommentForm(FlaskForm):
    body = TextAreaField('', validators=[DataRequired()])
    submit = SubmitField('Submit Comment')
    
    
    def validate_body(self, field):
        if current_user.is_anonymous:
            raise ValidationError("You are required to login")

app/main/__init__.py
from flask import Blueprint, session
from models import Permission

main = Blueprint("main", __name__)

@main.url_defaults
def add_language_code(endpoint, values):
    values.setdefault('lang_code', session['lang_code'])
    
@main.url_value_preprocessor
def pull_lang_code(endpoint, values):
    session['lang_code'] = values.pop('lang_code')

@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

from app.main import routes

app/main/routes.py
from flask import (redirect, url_for, render_template, request, current_app, 
                   flash, make_response, g, session, abort)
from app import db
from app.main import main
from flask_login import current_user, login_required
from app.auth.utils.decorators import permission_required
from app.main.forms import CommentForm
from models import Post, User, Permission, Comment
from flask_babel import get_locale, refresh

@main.before_request
def before_request():
    if session['lang_code'] not in current_app.config['LANGUAGES']:
        adapter = current_app.url_map.bind('')
        try:
            endpoint, args = adapter.match('/en' + request.full_path.rstrip('/ ?'))
            return redirect(url_for(endpoint, **args), 301)
        except:
            abort(404)
    if session['lang_code'] not in current_app.config['LANGUAGES']:
        abort(404)
    g.locale = str(get_locale())

# Homepage route
@main.route('/')
def home():
    
    context = {
        'title': 'Blog Page'
    }
    session['lang_code'] = request.accept_languages.best_match(current_app.config['LANGUAGES'])
    return render_template('main/index.html', **context)

# Blog page
@main.route('/blog')
def blog():
    
    page = request.args.get('page', 1, type=int)
    show_followed = False
    
    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed', ''))
    if show_followed:
        query = current_user.followed_posts
    else:
        query = Post.query
    pagination = query.order_by(Post.timestamp.desc()).\
                paginate(page=page, per_page=current_app.config['BLOG_POSTS_PER_PAGE'])
    posts = pagination.items
    recent_posts = Post.query.order_by(Post.timestamp.desc()).all()
    
    context = {
        'title': 'Blog Page',
        'posts': posts,
        'pagination': pagination,
        'recent_posts': recent_posts,
        'show_followed':show_followed
    }
    return render_template('main/blog.html', **context)

# Selection of all posts
@main.route('/all')
@login_required
def show_all():
    resp = make_response(redirect(url_for('main.blog')))
    resp.set_cookie('show_followed', '', max_age=30*24*60*30)
    return resp

# Selection of followed posts
@main.route('/followed')
@login_required
def show_followed():
    resp = make_response(redirect(url_for('main.blog')))
    resp.set_cookie('show_followed', '1', max_age=30*24*60*60)
    return resp
    

# Get user posts
@main.route('/user_posts/<username>')
def user_posts(username):
    
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter_by(author=user).\
                order_by(Post.timestamp.desc()).\
                paginate(page=page, per_page=current_app.config['BLOG_POSTS_PER_PAGE'])
    posts = pagination.items
    recent_posts = Post.query.order_by(Post.timestamp.desc()).all()
    
    context = {
        'title': f'{user.username}\'s Posts',
        'posts': posts,
        'pagination': pagination,
        'recent_posts': recent_posts,
        'user': user,
    }
    return render_template('main/user_posts.html', **context)

# User Profile page
@main.route('/user_profile/<username>')
def user_profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    
    context = {
        'title': f'{user.username}\'s Profile Page',
        'user': user
    }
    return render_template('main/user_profile.html', **context)

# Follow route
@main.route('/follow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user', "warning")
        return redirect(url_for('main.user_profile', username=username))
    if current_user.username == username:
        flash('You cannot follow yourself', "warning")
        return redirect(url_for('main.user_profile', username=username))
    if current_user.is_following(user):
        flash('You are already following this user', "info")
        return redirect(url_for('main.user_profile', username=username))
    current_user.follow(user)
    db.session.commit()
    flash(f'You are now following {username}', 'success')
    return redirect(url_for('main.user_profile', username=username))

# Unfollow user route
@main.route('/unfollow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user', 'warning')
        return redirect(url_for('main.user_profile', username=username))
    if not current_user.is_following(user):
        flash("You are not following this user", "warning")
        return redirect(url_for('main.user_profile', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash(f'You have unfollowed {username}', 'info')
    return redirect(url_for('main.user_profile', username=username))

# Get Followers of a particular user
@main.route('/followers/<username>')
def followers(username):
    # Get user
    user = User.query.filter_by(username=username).first() 
    if user is None:
        flash('Invalid user', 'warning')
        return redirect(url_for('main.user_profile', username=username))
    followers = user.followers.all()
    follows = [{'user':item.follower, 'date_followed':item.date_followed} for item in followers]
    
    context = {
        'title': f'Followers of {username}',
        'follows':follows,
        'user':user,
        'followers':'followers'
    }
    return render_template('main/followers.html', **context)

# Get followed users
@main.route('/following/<username>')
def following(username):
    
    # Get user
    user = User.query.filter_by(username=username).first() 
    if user is None:
        flash('Invalid user', 'warning')
        return redirect(url_for('main.user_profile', username=username))
    followed = user.followed.all()
    follows = [{'user':item.followed, 'date_followed':item.date_followed} for item in followed]
    
    context = {
        'title': f'Users Followed by {username}',
        'follows':follows,
        'user':user,
        'following':'following'
    }
    return render_template('main/followers.html', **context)

# View Blog Details
@main.route('/blog/<int:blog_id>/<slug>', methods=['GET', 'POST'])
def blog_details(blog_id, slug):
    
    form = CommentForm()
    post = Post.query.get_or_404(blog_id)
    page = request.args.get('page', default=1, type=int)
    
    if form.validate_on_submit():
        comment = Comment(body=form.body.data, author=current_user._get_current_object(), post=post)
        db.session.add(comment)
        db.session.commit()
        flash("Your comment has been added", "success")
        return redirect(url_for('main.blog_details', blog_id=post.id, slug=post.slug, _anchor='comments'))

    next_post = Post.query.order_by(Post.id.asc()).filter(Post.id > blog_id).first()
    prev_post = Post.query.order_by(Post.id.desc()).filter(Post.id < blog_id).first()
    recent_posts = Post.query.order_by(Post.timestamp.desc()).all()
    pagination = post.comments.order_by(Comment.comment_date.desc()).\
                paginate(page=page, per_page=current_app.config['COMMENTS_PER_PAGE'])
    comments = pagination.items
    
    
    context = {
        'title': f'{post.title}',
        'post': post,
        'next_post': next_post,
        'prev_post': prev_post,
        'recent_posts': recent_posts,
        'form': form,
        'comments':comments,
        'pagination': pagination
    }
    return render_template('main/blog_details.html', **context)

# Moderate(Enable) comments made by users
@main.route('/moderate/enable/<int:comment_id>')
@login_required
@permission_required(Permission.MODERATE)
def moderate_enable(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.disabled = False
    db.session.commit()
    flash('Comment enabled successfully', 'info')
    return redirect(url_for('main.blog_details', blog_id=comment.post.id, 
                            slug=comment.post.slug, _anchor='comments'))
    
# Moderate(Disable) comments made by users
@main.route('/moderate/disable/<int:comment_id>')
@login_required
@permission_required(Permission.MODERATE)
def moderate_disable(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.disabled = True
    db.session.commit()
    flash('Comment disabled', 'warning')
    return redirect(url_for('main.blog_details', blog_id=comment.post.id, 
                            slug=comment.post.slug, _anchor='comments'))

        

app/templates/main/layout/main_layout.html
<!DOCTYPE html>
<html lang="en">
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="author" content="INSPIRO" />
<meta name="description" content="Themeforest Template Polo, html template">
<link rel="icon" type="image/png" href="{{ url_for('static', filename='main/images/favicon.png') }}">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- Document title -->
{% if title %}
<title>Santa-Blog -- {{ title }}</title>
{% else %}
<title>Santa-Blog</title>
{% endif %}
<!-- Stylesheets & Fonts -->
<link href="{{ url_for('static', filename='main/css/plugins.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='main/css/style.css') }}" rel="stylesheet">
<!-- DataTables css -->
<link href="{{ url_for('static', filename='main/plugins/datatables/datatables.min.css') }}" 
        rel='stylesheet' />
<!-- Include moment library -->
{{ moment.include_moment() }}
{{ moment.lang(g.locale) }}
</head>

<body>
    <div class="body-inner">
        <!-- Header -->
        <header id="header" data-fullwidth="true">
            <div class="header-inner">
                <div class="container">
                    <!--Logo-->
                    <div id="logo">
                        <a href="{{ url_for('main.home') }}">
                            <span class="logo-default">SANTA-BLOG</span>
                            <span class="logo-dark">SANTA-BLOG</span>
                        </a>
                    </div>
                    <!--End: Logo-->
                    <!-- Search -->
                    <div id="search"><a id="btn-search-close" class="btn-search-close" aria-label="Close search form"><i
                                class="icon-x"></i></a>
                        <form class="search-form" action="search-results-page.html" method="get">
                            <input class="form-control" name="q" type="text" placeholder="Type & Search..." />
                            <span class="text-muted">Start typing & press "Enter" or "ESC" to close</span>
                        </form>
                    </div>
                    <!-- end: search -->
                    <!--Header Extras-->
                    <div class="header-extras">
                        <ul>
                            <li>
                                <a id="btn-search" href="#"> <i class="icon-search"></i></a>
                            </li>
                            <li>
                                <div class="p-dropdown">
                                    <a href="#"><i class="icon-globe"></i>
                                        <span>{{ session['lang_code']|upper }}</span>
                                    </a>
                                    <ul class="p-dropdown-content">
                                        
                                        <li>
                                            <a href="{{ url_for(request.endpoint, lang_code='en') }}">English</a>
                                        </li>
                                        <li>
                                            <a href="{{ url_for(request.endpoint, lang_code='fr') }}">French</a>
                                        </li>
                                        <li>
                                            <a href="{{ url_for(request.endpoint, lang_code='es') }}">Spanish</a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <!--end: Header Extras-->
                    <!--Navigation Resposnive Trigger-->
                    <div id="mainMenu-trigger">
                        <a class="lines-button x"><span class="lines"></span></a>
                    </div>
                    <!--end: Navigation Resposnive Trigger-->
                    <!--Navigation-->
                    <div id="mainMenu">
                        <div class="container">
                            <nav>
                                <ul>
                                    <li><a href="{{ url_for('main.home') }}">Home</a></li>
                                    <li class="dropdown mega-menu-item"><a href="{{ url_for('main.blog') }}">Blog</a>
                                        <!-- <ul class="dropdown-menu">
                                            <li class="mega-menu-content">
                                                <div class="row">
                                                    <div class="col-lg-2-5">
                                                        <ul>
                                                            <li class="mega-menu-title">Masonry</li>
                                                            <li><a href="blog-masonry-2.html">Two Columns</a></li>
                                                            <li><a href="blog-masonry-3.html">Three Columns<span
                                                                        class="badge bg-danger">HOT</span></a></li>
                                                            <li><a href="blog-masonry-4.html">Four Columns</a></li>
                                                            <li><a href="blog-masonry-sidebar.html">Sidebar version</a>
                                                            </li>
                                                            <li><a href="blog-masonry-no-page-title.html">No page
                                                                    title</a></li>
                                                            <li><a href="blog-masonry-wide.html">Wide version</a></li>
                                                            <li><a href="blog-masonry-load-more.html">Load More</a></li>
                                                            <li><a href="blog-masonry-infinite-scroll.html">Infinite
                                                                    Scroll</a></li>
                                                            <li><a href="blog-masonry-filter.html">Filter Categories</a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul> -->
                                    </li>
                                    {% if current_user.is_authenticated %}
                                    <li><a href="{{ url_for('dashboard.dashboard_home') }}">Dashboard</a></li>
                                    {% else %}
                                    <li><a href="{{ url_for('dashboard.dashboard_home') }}">Portal</a></li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <!--END: NAVIGATION-->
                </div>
            </div>
        </header>
        <!-- end: Header -->
        <!-- Content -->
        {% block content %}
        {% endblock content %}
        <!-- end: Content -->
        <!-- Footer -->
        <footer id="footer">
            <div class="footer-content">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-5">
                            <div class="widget">
                                <div class="widget-title">Polo HTML5 Template</div>
                                <p class="mb-5">Built with love in Fort Worth, Texas, USA<br> All rights reserved.
                                    Copyright © 2021. INSPIRO.</p>
                                <a href="https://themeforest.net/item/polo-responsive-multipurpose-html5-template/13708923"
                                    class="btn btn-inverted" target="_blank">Purchase Now</a>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="row">
                                <div class="col-lg-3">
                                    <div class="widget">
                                        <div class="widget-title">Discover</div>
                                        <ul class="list">
                                            <li><a href="#">Features</a></li>
                                            <li><a href="#">Layouts</a></li>
                                            <li><a href="#">Corporate</a></li>
                                            <li><a href="#">Updates</a></li>
                                            <li><a href="#">Pricing</a></li>
                                            <li><a href="#">Customers</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="widget">
                                        <div class="widget-title">Features</div>
                                        <ul class="list">
                                            <li><a href="#">Layouts</a></li>
                                            <li><a href="#">Headers</a></li>
                                            <li><a href="#">Widgets</a></li>
                                            <li><a href="#">Footers</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="widget">
                                        <div class="widget-title">Pages</div>
                                        <ul class="list">
                                            <li><a href="#">Portfolio</a></li>
                                            <li><a href="#">Blog</a></li>
                                            <li><a href="#">Shop</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="widget">
                                        <div class="widget-title">Support</div>
                                        <ul class="list">
                                            <li><a href="#">Help Desk</a></li>
                                            <li><a href="#">Documentation</a></li>
                                            <li><a href="#">Contact Us</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright-content">
                <div class="container">
                    <div class="copyright-text text-center">&copy; 2021 POLO - Responsive Multi-Purpose HTML5 Template.
                        All Rights Reserved.<a href="https://www.inspiro-media.com" target="_blank" rel="noopener">
                            INSPIRO</a> </div>
                </div>
            </div>
        </footer>
        <!-- end: Footer -->
    </div>
    <!-- end: Body Inner -->
    <!-- Scroll top -->
    <a id="scrollTop"><i class="icon-chevron-up"></i><i class="icon-chevron-up"></i></a>
    <!--Plugins-->
    <script src="{{ url_for('static', filename='main/js/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='main/js/plugins.js') }}"></script>
    <!--Template functions-->
    <script src="{{ url_for('static', filename='main/js/functions.js') }}"></script>

    <!--Datatables plugin files-->
    <script src="{{ url_for('static', filename='main/plugins/datatables/datatables.min.js') }}"></script>
    <script>
        $(document).ready(function(){
            $("#datatable").DataTable();
        })
    </script>
</body>

</html>