app/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, TextAreaField
from wtforms.validators import DataRequired
from flask_ckeditor import CKEditorField

class ProfileForm(FlaskForm):
    username = StringField('Username')
    first_name = StringField('First Name')
    last_name = StringField('Last Name')
    middle_name = StringField('Middle Name')
    mobile_no = StringField('Mobile Number')
    email = EmailField('Email')
    bio = TextAreaField('Bio')
    address = StringField('Address')
    job_title = StringField('Job Title')

# Blog Post Form   
class PostForm(FlaskForm):
    title = StringField('Title')
    body = CKEditorField('What\'s on your mind?', validators=[DataRequired()])
    
# Admin Blog Post Form   
class AdminPostForm(FlaskForm):
    title = StringField('Title')
    author = StringField('Author')
    body = CKEditorField('Blog Details', validators=[DataRequired()])

app/dashboard/__init__.py
from flask import Blueprint

# Create Blueprint name
dashboard = Blueprint('dashboard', __name__)

# Import routes
from app.dashboard import routes

app/dashboard/routes.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user
from app import db
from models import Post
from app.dashboard import dashboard
from app.auth.utils.decorators import admin_required
from app.dashboard.forms import PostForm, ProfileForm, AdminPostForm
from app.dashboard.utils import save_profile_image, save_header_image

@dashboard.route('/')
@login_required
def dashboard_home():
    
    context = {
        'title': 'Home',
        'submenu': 'Home'
        
    }
    return render_template('dashboard/dashboard.html', **context)

@dashboard.route('/landing_page')
def landingpage():
    
    context = {
        'title': 'Landing Page'
    }
    return render_template('dashboard/landingpage.html', **context)

# Profile Page
@dashboard.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = ProfileForm()
    # user = User.query.filter_by(email=current_user.email).first()
    
    if form.validate_on_submit():
        if request.files.get('profile_pic'):
            picture_file = save_profile_image(request.files.get('profile_pic'))
            current_user.image = picture_file 
        if request.files.get('header_image'):
            header_image = save_header_image(request.files.get('header_image'))
            current_user.header = header_image 
        current_user.country =  request.form.get('country')
        current_user.username = form.username.data
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.middle_name = form.middle_name.data
        current_user.email = form.email.data
        current_user.bio = form.bio.data
        current_user.job_title = form.job_title.data
        current_user.mobile_no = form.mobile_no.data
        current_user.address = form.address.data
        # current_user.address_no = form.address_no.data
        db.session.add(current_user)
        db.session.commit()
        flash("Profile updated successfully", "success")
        return redirect(url_for('dashboard.profile'))
    
    form.username.data = current_user.username
    form.first_name.data = current_user.first_name
    form.last_name.data = current_user.last_name
    form.middle_name.data = current_user.middle_name
    form.email.data = current_user.email
    form.bio.data = current_user.bio
    form.job_title.data = current_user.job_title
    form.mobile_no.data = current_user.mobile_no
    form.address.data = current_user.address
    
    context = {
        'title': 'Profile Page',
        'form': form,
        'submenu': 'Settings'
    }
    return render_template('dashboard/profile.html', **context)

# Post blog route
@dashboard.route('/post_blog', methods=['GET', 'POST'])
@login_required
def post_blog():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, body_html=form.body.data, 
                    author=current_user._get_current_object())
        db.session.add(post)
        db.session.commit()
        flash("New blog post has been added successfully", "success")
        return redirect(url_for('dashboard.post_blog'))
    
    context = {
        'title': 'Post Blog',
        'form': form,
        'submenu': 'Blog'
    }
    return render_template('dashboard/post_blog.html', **context)

# View Posts
@dashboard.route('/view_posts')
@login_required
def view_posts():
    
    posts = Post.query.filter_by(author=current_user._get_current_object()).all()
    
    context = {
        'title': 'View Posts',
        'posts': posts,
        'submenu': 'Blog'
    }
    return render_template('dashboard/view_posts.html', **context)

# Update Blog Post
@dashboard.route('/update_blog/<int:blog_id>', methods=['GET', 'POST'])
@login_required
def update_blog(blog_id):
    
    form = PostForm()
    # Get the post
    post = Post.query.filter_by(id=blog_id).first_or_404()
    
    if form.validate_on_submit():
        post.title = form.title.data
        post.body_html = form.body.data
        db.session.commit()
        flash("Blog post has been updated", "success")
        return redirect(url_for('dashboard.view_posts'))
    
    form.title.data = post.title
    form.body.data = post.body_html
    context = {
        'title': 'Update Blog',
        'form': form,
        'submenu': 'Blog',
    }
    return render_template('dashboard/update_blog.html', **context)

# Delete Blog post
@dashboard.route('/delete_post<int:blog_id>', methods=['POST'])
@login_required
def delete_post(blog_id):
    post = Post.query.filter_by(id=blog_id).first_or_404()
    if request.method == "POST":
        db.session.delete(post)
        db.session.commit()
        flash("Post has been deleted", "info")
        return redirect(url_for('dashboard.view_posts'))

# Manage blog posts
@dashboard.route('/admin_view_posts')
@login_required
@admin_required
def admin_view_posts():
    
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    
    context = {
        'title': 'Admin View Posts',
        'posts': posts,
        'submenu': 'Settings'
    }
    return render_template('dashboard/admin_view_posts.html', **context)

# Admin Update Blog Post
@dashboard.route('/admin_update_blog/<int:blog_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def admin_update_blog(blog_id):
    
    form = AdminPostForm()
    # Get the post
    post = Post.query.filter_by(id=blog_id).first_or_404()
    
    if form.validate_on_submit():
        post.title = form.title.data
        post.author.username = form.author.data
        post.body_html = form.body.data
        db.session.commit()
        flash("Blog post has been updated", "success")
        return redirect(url_for('dashboard.admin_view_posts'))
    
    form.title.data = post.title
    form.author.data = post.author.username
    form.body.data = post.body_html
    context = {
        'title': 'Admin Update Blog',
        'form': form,
        'submenu': 'Settings',
    }
    return render_template('dashboard/admin_update_blog.html', **context)

# Admin Delete Blog post
@dashboard.route('/admin_delete_post<int:blog_id>', methods=['POST'])
@login_required
@admin_required
def admin_delete_post(blog_id):
    post = Post.query.filter_by(id=blog_id).first_or_404()
    if request.method == "POST":
        db.session.delete(post)
        db.session.commit()
        flash("Post has been deleted", "info")
        return redirect(url_for('dashboard.admin_view_posts'))

app/templates/dashboard/admin_update_blog.html
{% extends "dashboard/layout/dashboard_layout.html" %}
{% from "dashboard/forms_macro.html" import dashboard_forms %}
{% block content %}
<!-- Row -->
<div class="row">
    <div class="col-lg-12">
        <div class="card card-outline-info">
            <div class="card-body">
                <form method="POST">
                    {{ form.csrf_token }}
                    <div class="form-body">
                        <div class="row p-t-20">
                            <div class="col-md-6">
                                {{dashboard_forms(form.title, placeholder="Enter blog title", required="")}}
                                {{dashboard_forms(form.author, placeholder="Author", required="", readonly=true)}}
                                {{dashboard_forms(form.body, placeholder="", rows=5)}}
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-success"> 
                            <i class="fa fa-check"></i>Update Post
                        </button>
                    </div>
                </form>
                {{ ckeditor.config(name='body') }}
            </div>
        </div>
    </div>
</div>
<!-- Row -->
{% endblock content %}

app/templates/dashboard/admin_view_posts.html
{% extends "dashboard/layout/dashboard_layout.html" %}
{% from "dashboard/forms_macro.html" import dashboard_forms %}
{% block content %}
<!-- Row -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">View All Posts</h4>
                <h6 class="card-subtitle">All Blog Posts</h6>
                <div class="table-responsive m-t-40">
                    <table id="myTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Author</th>
                                <th>Title</th>
                                <th>Body</th>
                                <th class="text-nowrap">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for post in posts %}
                            <tr>
                                <td>{{ loop.index }}</td>
                                <td>{{ post.author.username }}</td>
                                <td>{{ post.title }}</td>
                                <td>
                                    {% if post.body_html|length > 150 %}
                                    {{ post.body_html[:150]|safe }}...
                                    {% else %}
                                    {{ post.body_html|safe }}
                                    {% endif %}
                                </td>
                                <td class="text-nowrap">
                                    <a href="{{ url_for('dashboard.admin_update_blog', blog_id=post.id) }}" 
                                        data-toggle="tooltip" data-original-title="Edit"> 
                                        <i class="fa fa-pencil text-inverse m-r-10"></i> 
                                    </a>
                                    <a href="#" data-toggle="modal" data-target="#myModal-{{ post.id }}"> 
                                        <i class="fa fa-close text-danger"></i> 
                                    </a>
                                </td>
                            </tr>
                            <div id="myModal-{{ post.id }}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModal-{{ post.id }}Label" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title" id="myModal-{{ post.id }}Label">Delete Blog Post?</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                        </div>
                                        <div class="modal-body">
                                            <h4>Title: {{ post.title }}</h4>
                                            <h4>Author: {{ post.author.username }}</h4>
                                            <br>
                                            <p>Are you sure you want to delete this post 
                                                written by {{ post.author.username }}?
                                            </p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-info waves-effect" 
                                                data-dismiss="modal">Close
                                            </button>
                                            <form action="{{ url_for('dashboard.admin_delete_post', blog_id=post.id) }}" 
                                                method="POST">
                                                <button type="submit" class="btn btn-danger 
                                                    waves-effect">Delete
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Row -->
{% endblock content %}

app/templates/dashboard/dashboard.html
{% extends "dashboard/layout/dashboard_layout.html" %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                This is some text within a card block.
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/dashboard/forms_macro.html
{% macro dashboard_forms(fieldname, placeholderValue) %}
<div class="form-group">
    {{ fieldname.label(class="control-label") }}
    {% if fieldname.errors %}
    <div class="form-group has-danger">
        {{ fieldname(class="form-control form-control-danger", placeholder=placeholderValue, **kwargs) }}
        <div class="form-control-feedback">
            {% for error in fieldname.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
    </div>
    {% else %}
    {{ fieldname(class="form-control", placeholder=placeholderValue, **kwargs) }}
    {% endif %}
</div>
{% endmacro %}

app/templates/dashboard/landingpage.html
{% extends "dashboard/layout/landingpage_layout.html" %}
{% block content %}
<div class="fix-width">
    <div class="row banner-text justify-content-center">
        {% if current_user.is_authenticated %}
        <div class="col-md-8 m-t-18 text-center">
            <h1 style="color: #154a6c;">Welcome {{ current_user.username }} <br> to <br>
                <span style="color: #8fad55;">
                    Santa Blog!
                </span>
            </h1>
            <p class="subtext">
                <span class="font-medium">
                    Please click on Dashboard to manage your account
                </span>
            </p>
        </div>
        {% elif current_user.is_anonymous %}
        <div class="col-md-8 m-t-20 text-center">
            <h1 style="color: #154a6c;">Welcome to
                <span style="color: #8fad55;">
                    Santa Blog
                </span>
            </h1>
            <p class="subtext">
                <span class="font-medium">
                    Please login to access the Management Dashboard
                </span>
            </p>
        </div>
        {% endif %}

        <div class="col-md-12 text-center">
            <div class="hero-banner">
                <img src="{{ url_for('static', filename='landingpage/images/banner.jpg') }}" alt="Admin Press template"
                    class="img-fluid" />
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/dashboard/post_blog.html
{% extends "dashboard/layout/dashboard_layout.html" %}
{% from "dashboard/forms_macro.html" import dashboard_forms %}
{% block content %}
<!-- Row -->
<div class="row">
    <div class="col-lg-12">
        <div class="card card-outline-info">
            <div class="card-body">
                <form method="POST">
                    {{ form.csrf_token }}
                    <div class="form-body">
                        <div class="row p-t-20">
                            <div class="col-md-6">
                                {{dashboard_forms(form.title, placeholder="Enter blog title", required="")}}
                                {{dashboard_forms(form.body, placeholder="", required="", rows=5)}}
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-success"> 
                            <i class="fa fa-check"></i>Add Post
                        </button>
                    </div>
                </form>
                {{ ckeditor.config(name='body') }}
            </div>
        </div>
    </div>
</div>
<!-- Row -->
{% endblock content %}

app/templates/dashboard/profile_macros.html
{% macro profile_forms(fieldname, placeholderValue) %}
<div class="form-group">
    {{ fieldname.label(class="col-md-12") }}
    <div class="col-md-12">
        {% if fieldname.errors %}
        <div class="form-group has-danger">
            {{ fieldname(class="form-control form-control-danger", placeholder=placeholderValue, **kwargs) }}
            <div class="form-control-feedback">
                {% for error in fieldname.errors %}
                <span> {{ error }} </span>
                {% endfor %}
            </div>
        </div>
        {% else %}
        {{ fieldname(class="form-control", placeholder=placeholderValue, **kwargs) }}
        {% endif %}
    </div>
</div>
{% endmacro %}

app/templates/dashboard/update_blog.html
{% extends "dashboard/layout/dashboard_layout.html" %}
{% from "dashboard/forms_macro.html" import dashboard_forms %}
{% block content %}
<!-- Row -->
<div class="row">
    <div class="col-lg-12">
        <div class="card card-outline-info">
            <div class="card-body">
                <form method="POST">
                    {{ form.csrf_token }}
                    <div class="form-body">
                        <div class="row p-t-20">
                            <div class="col-md-6">
                                {{dashboard_forms(form.title, placeholder="Enter blog title", required="")}}
                                {{dashboard_forms(form.body, placeholder="", required="", rows=5)}}
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-success"> 
                            <i class="fa fa-check"></i>Update Post
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Row -->
{% endblock content %}

app/templates/dashboard/view_posts.html
{% extends "dashboard/layout/dashboard_layout.html" %}
{% from "dashboard/forms_macro.html" import dashboard_forms %}
{% block content %}
<!-- Row -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">View Posts</h4>
                <h6 class="card-subtitle">My Blog Posts</h6>
                <div class="table-responsive m-t-40">
                    <table id="myTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Title</th>
                                <th>Body</th>
                                <th class="text-nowrap">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for post in posts %}
                            <tr>
                                <td>{{ loop.index }}</td>
                                <td>{{ post.title }}</td>
                                <td>
                                    {% if post.body_html|length > 150 %}
                                    {{ post.body_html[:150]|safe }}...
                                    {% else %}
                                    {{ post.body_html|safe }}
                                    {% endif %}
                                </td>
                                <td class="text-nowrap">
                                    <a href="{{ url_for('dashboard.update_blog', blog_id=post.id) }}" 
                                        data-toggle="tooltip" data-original-title="Edit"> 
                                        <i class="fa fa-pencil text-inverse m-r-10"></i> 
                                    </a>
                                    <a href="#" data-toggle="modal" data-target="#myModal-{{ post.id }}"> 
                                        <i class="fa fa-close text-danger"></i> 
                                    </a>
                                </td>
                            </tr>
                            <div id="myModal-{{ post.id }}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModal-{{ post.id }}Label" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title" id="myModal-{{ post.id }}Label">Delete Blog Post?</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                        </div>
                                        <div class="modal-body">
                                            <h4>Title: {{ post.title }}</h4>
                                            <p>Are you sure you want to delete this post?</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-info waves-effect" 
                                                data-dismiss="modal">Close
                                            </button>
                                            <form action="{{ url_for('dashboard.delete_post', blog_id=post.id) }}" 
                                                method="POST">
                                                <button type="submit" class="btn btn-danger 
                                                    waves-effect">Delete
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Row -->
{% endblock content %}