app/main/forms.py
from ast import Sub
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired, ValidationError
from flask_login import current_user

class CommentForm(FlaskForm):
    body = TextAreaField('', validators=[DataRequired()])
    submit = SubmitField('Submit Comment')
    
    
    def validate_body(self, field):
        if current_user.is_anonymous:
            raise ValidationError("You are required to login")

app/main/__init__.py
from flask import Blueprint, session
from models import Permission

main = Blueprint("main", __name__)

@main.url_defaults
def add_language_code(endpoint, values):
    values.setdefault('lang_code', session['lang_code'])
    
@main.url_value_preprocessor
def pull_lang_code(endpoint, values):
    session['lang_code'] = values.pop('lang_code')

@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

from app.main import routes

app/main/routes.py
from flask import (redirect, url_for, render_template, request, current_app, 
                   flash, make_response, g, session, abort)
from app import db
from app.main import main
from flask_login import current_user, login_required
from app.auth.utils.decorators import permission_required
from app.main.forms import CommentForm
from models import Post, User, Permission, Comment
from flask_babel import get_locale, refresh

@main.before_request
def before_request():
    if session['lang_code'] not in current_app.config['LANGUAGES']:
        adapter = current_app.url_map.bind('')
        try:
            endpoint, args = adapter.match('/en' + request.full_path.rstrip('/ ?'))
            return redirect(url_for(endpoint, **args), 301)
        except:
            abort(404)
    if session['lang_code'] not in current_app.config['LANGUAGES']:
        abort(404)
    g.locale = str(get_locale())

# Homepage route
@main.route('/')
def home():
    
    context = {
        'title': 'Blog Page'
    }
    session['lang_code'] = request.accept_languages.best_match(current_app.config['LANGUAGES'])
    return render_template('main/index.html', **context)

# Blog page
@main.route('/blog')
def blog():
    
    page = request.args.get('page', 1, type=int)
    show_followed = False
    
    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed', ''))
    if show_followed:
        query = current_user.followed_posts
    else:
        query = Post.query
    pagination = query.order_by(Post.timestamp.desc()).\
                paginate(page=page, per_page=current_app.config['BLOG_POSTS_PER_PAGE'])
    posts = pagination.items
    recent_posts = Post.query.order_by(Post.timestamp.desc()).all()
    
    context = {
        'title': 'Blog Page',
        'posts': posts,
        'pagination': pagination,
        'recent_posts': recent_posts,
        'show_followed':show_followed
    }
    return render_template('main/blog.html', **context)

# Selection of all posts
@main.route('/all')
@login_required
def show_all():
    resp = make_response(redirect(url_for('main.blog')))
    resp.set_cookie('show_followed', '', max_age=30*24*60*30)
    return resp

# Selection of followed posts
@main.route('/followed')
@login_required
def show_followed():
    resp = make_response(redirect(url_for('main.blog')))
    resp.set_cookie('show_followed', '1', max_age=30*24*60*60)
    return resp
    

# Get user posts
@main.route('/user_posts/<username>')
def user_posts(username):
    
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter_by(author=user).\
                order_by(Post.timestamp.desc()).\
                paginate(page=page, per_page=current_app.config['BLOG_POSTS_PER_PAGE'])
    posts = pagination.items
    recent_posts = Post.query.order_by(Post.timestamp.desc()).all()
    
    context = {
        'title': f'{user.username}\'s Posts',
        'posts': posts,
        'pagination': pagination,
        'recent_posts': recent_posts,
        'user': user,
    }
    return render_template('main/user_posts.html', **context)

# User Profile page
@main.route('/user_profile/<username>')
def user_profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    
    context = {
        'title': f'{user.username}\'s Profile Page',
        'user': user
    }
    return render_template('main/user_profile.html', **context)

# Follow route
@main.route('/follow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user', "warning")
        return redirect(url_for('main.user_profile', username=username))
    if current_user.username == username:
        flash('You cannot follow yourself', "warning")
        return redirect(url_for('main.user_profile', username=username))
    if current_user.is_following(user):
        flash('You are already following this user', "info")
        return redirect(url_for('main.user_profile', username=username))
    current_user.follow(user)
    db.session.commit()
    flash(f'You are now following {username}', 'success')
    return redirect(url_for('main.user_profile', username=username))

# Unfollow user route
@main.route('/unfollow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user', 'warning')
        return redirect(url_for('main.user_profile', username=username))
    if not current_user.is_following(user):
        flash("You are not following this user", "warning")
        return redirect(url_for('main.user_profile', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash(f'You have unfollowed {username}', 'info')
    return redirect(url_for('main.user_profile', username=username))

# Get Followers of a particular user
@main.route('/followers/<username>')
def followers(username):
    # Get user
    user = User.query.filter_by(username=username).first() 
    if user is None:
        flash('Invalid user', 'warning')
        return redirect(url_for('main.user_profile', username=username))
    followers = user.followers.all()
    follows = [{'user':item.follower, 'date_followed':item.date_followed} for item in followers]
    
    context = {
        'title': f'Followers of {username}',
        'follows':follows,
        'user':user,
        'followers':'followers'
    }
    return render_template('main/followers.html', **context)

# Get followed users
@main.route('/following/<username>')
def following(username):
    
    # Get user
    user = User.query.filter_by(username=username).first() 
    if user is None:
        flash('Invalid user', 'warning')
        return redirect(url_for('main.user_profile', username=username))
    followed = user.followed.all()
    follows = [{'user':item.followed, 'date_followed':item.date_followed} for item in followed]
    
    context = {
        'title': f'Users Followed by {username}',
        'follows':follows,
        'user':user,
        'following':'following'
    }
    return render_template('main/followers.html', **context)

# View Blog Details
@main.route('/blog/<int:blog_id>/<slug>', methods=['GET', 'POST'])
def blog_details(blog_id, slug):
    
    form = CommentForm()
    post = Post.query.get_or_404(blog_id)
    page = request.args.get('page', default=1, type=int)
    
    if form.validate_on_submit():
        comment = Comment(body=form.body.data, author=current_user._get_current_object(), post=post)
        db.session.add(comment)
        db.session.commit()
        flash("Your comment has been added", "success")
        return redirect(url_for('main.blog_details', blog_id=post.id, slug=post.slug, _anchor='comments'))

    next_post = Post.query.order_by(Post.id.asc()).filter(Post.id > blog_id).first()
    prev_post = Post.query.order_by(Post.id.desc()).filter(Post.id < blog_id).first()
    recent_posts = Post.query.order_by(Post.timestamp.desc()).all()
    pagination = post.comments.order_by(Comment.comment_date.desc()).\
                paginate(page=page, per_page=current_app.config['COMMENTS_PER_PAGE'])
    comments = pagination.items
    
    
    context = {
        'title': f'{post.title}',
        'post': post,
        'next_post': next_post,
        'prev_post': prev_post,
        'recent_posts': recent_posts,
        'form': form,
        'comments':comments,
        'pagination': pagination
    }
    return render_template('main/blog_details.html', **context)

# Moderate(Enable) comments made by users
@main.route('/moderate/enable/<int:comment_id>')
@login_required
@permission_required(Permission.MODERATE)
def moderate_enable(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.disabled = False
    db.session.commit()
    flash('Comment enabled successfully', 'info')
    return redirect(url_for('main.blog_details', blog_id=comment.post.id, 
                            slug=comment.post.slug, _anchor='comments'))
    
# Moderate(Disable) comments made by users
@main.route('/moderate/disable/<int:comment_id>')
@login_required
@permission_required(Permission.MODERATE)
def moderate_disable(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.disabled = True
    db.session.commit()
    flash('Comment disabled', 'warning')
    return redirect(url_for('main.blog_details', blog_id=comment.post.id, 
                            slug=comment.post.slug, _anchor='comments'))

        

app/templates/main/blog.html
{% extends "main/layout/main_layout.html" %}
{% block content %}
<section id="page-content" class="sidebar-right">
    <div class="container">
        <div class="row">
            <!-- post content -->
            <div class="content col-lg-9">
                <!-- Page title -->
                <div class="page-title">
                    <h1>Blog</h1>
                    <div class="breadcrumb float-left">
                        <ul>
                            <li><a href="#">Home</a>
                            </li>
                            <li class="active"><a href="#">Blog</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- end: Page title -->
                <!-- Portfolio Filter -->
                <hr>
                <div class="tabs tabs-clean">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link {% if not show_followed %} active {% endif %}" href="{{ url_for('main.show_all') }}">
                                All
                            </a>
                        </li>
                        {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link {% if show_followed %} active {% endif %}" href="{{ url_for('main.show_followed') }}">
                                Followed
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                <!-- end: Portfolio Filter -->
                <!-- Blog -->
                <div id="blog" class="grid-layout post-3-columns m-b-30" data-item="post-item">
                    <!-- Post item-->
                    {% for post in posts %}
                    <div class="post-item border">
                        <div class="post-item-wrap">
                            <div class="post-image">
                                <a href="#">
                                    <img alt="" src="{{ url_for('static', filename='main/images/blog/12.jpg') }}">
                                </a>
                                <span class="post-meta-category"><a href="">Lifestyle</a></span>
                            </div>
                            <div class="post-item-description">
                                <span class="post-meta-date">
                                    <i class="fa fa-calendar-o"></i>
                                    {{ post.timestamp.strftime('%b %d, %Y') }}
                                </span>
                                <span class="post-meta-comments">
                                    <a href="{{ url_for('main.blog_details', blog_id=post.id, slug=post.slug, _anchor='comments') }}">
                                        <i class="fa fa-comments-o"></i>
                                        {{ post.comments.count() }} 
                                        {% if post.comments.count() < 2 %}
                                        Comment
                                        {% else %}
                                        Comments
                                        {% endif %}
                                    </a>
                                </span>
                                <h2><a href="{{ url_for('main.blog_details', blog_id=post.id, slug=post.slug) }}">{{ post.title }}</a></h2>
                                {% if post.body_html|length > 150 %}
                                    <p>{{ post.body_html[:150]|safe }}...</p>
                                {% else %}
                                    <p>{{ post.body_html|safe }}</p>
                                {% endif %}
                                <a href="{{ url_for('main.blog_details', blog_id=post.id, slug=post.slug) }}" 
                                    class="item-link">Read More <i class="icon-chevron-right"></i>
                                </a>
                                <hr>
                                <div> 
                                    <a href="{{ url_for('main.user_profile', username=post.author.username) }}" 
                                        data-bs-toggle="tooltip" data-bs-placement="top" 
                                        data-bs-title="View {{ post.author.username }}'s profile">
                                        <img src="{{ url_for('static', filename='dashboard/profile_pics/'+post.author.image) }}"
                                        style="border-radius: 50%; width: 28px; height: 28px; float:left; margin-right: 5px;">
                                    </a>
                                    <p>by 
                                        <a href="{{ url_for('main.user_posts', username=post.author.username) }}">
                                            {{ post.author.username }}
                                        </a> {{ moment(post.timestamp).fromNow() }} 
                                    </p>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    {% endfor %}
                    <!-- end: Post item-->
                </div>
                <!-- end: Blog -->
                <!-- Pagination -->
                <ul class="pagination">
                    {% for page_num in pagination.iter_pages(left_edge=2, right_edge=2, left_current=3, right_current=5) %}
                    {% if page_num %}
                        {% if pagination.page == page_num %}
                        <li class="page-item active">
                            <a class="page-link" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
                        </li>
                        {% endif %}
                    {% else %}
                    ...
                    {% endif %}
                    {% endfor %}
                </ul>
                <!-- end: Pagination -->
            </div>
            <!-- end: post content -->
            <!-- Sidebar-->
            <div class="sidebar sticky-sidebar col-lg-3">
                <!--Tabs with Posts-->
                <div class="widget ">
                    <h4 class="widget-title">Recent Posts</h4>
                    <div class="post-thumbnail-list">
                        {% for post in recent_posts[:5] %}
                        <div class="post-thumbnail-entry">
                            <img alt="" src="{{ url_for('static', filename='main/images/blog/thumbnail/5.jpg') }}">
                            <div class="post-thumbnail-content">
                                <a href="{{ url_for('main.blog_details', blog_id=post.id, slug=post.slug) }}">
                                    {{ post.title }}
                                </a>
                                <span class="post-date"><i class="icon-clock"></i> 
                                    {{ moment(post.timestamp).fromNow() }}
                                </span>
                                <span class="post-category"><i class="fa fa-tag"></i> Technology</span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <!--End: Tabs with Posts-->
                <!-- Twitter widget -->
                <div class="widget widget-tweeter" data-username="envato" data-limit="2">
                    <h4 class="widget-title">Recent Tweets</h4>
                </div>
                <!-- end: Twitter widget-->
                <!--widget tags -->
                <div class="widget  widget-tags">
                    <h4 class="widget-title">Tags</h4>
                    <div class="tags">
                        <a href="#">Design</a>
                        <a href="#">Portfolio</a>
                        <a href="#">Digital</a>
                        <a href="#">Branding</a>
                        <a href="#">HTML</a>
                        <a href="#">Clean</a>
                        <a href="#">Peace</a>
                        <a href="#">Love</a>
                        <a href="#">CSS3</a>
                        <a href="#">jQuery</a>
                    </div>
                </div>
                <!--end: widget tags -->
                <!--widget newsletter-->
                <div class="widget  widget-newsletter">
                    <form class="widget-subscribe-form" novalidate action="include/subscribe-form.php"
                        role="form" method="post">
                        <h4 class="widget-title">Newsletter</h4>
                        <small>Stay informed on our latest news!</small>
                        <div class="input-group">
                            <input type="email" required name="widget-subscribe-form-email"
                                class="form-control required email" placeholder="Enter your Email">
                            <span class="input-group-btn">
                                <button type="submit" id="widget-subscribe-submit-button"
                                    class="btn btn-primary"><i class="fa fa-paper-plane"></i></button>
                            </span>
                        </div>
                    </form>
                </div>
                <!--end: widget newsletter-->
            </div>
            <!-- end: Sidebar-->
        </div>
    </div>
</section>
{% endblock content %}

app/templates/main/followers.html
{% extends "main/layout/main_layout.html" %}
{% block content %}
<section id="page-content" class="no-sidebar">
    <div class="container">
        <!-- DataTable -->
        {% if followers %}
        <div class="row mb-3">
            <div class="col-lg-6">
                <h4>Followers</h4>
                <p>Users following {{ user.username }}</p>
            </div>
            <div class="col-lg-6 text-end">
                <a href="{{ url_for('main.following', username=user.username) }}" 
                    class="btn btn-light"><i class="fa fa-users"></i> Following
                </a>
                <div id="export_buttons" class="mt-2"></div>
            </div>
        </div>
        {% elif following %}
        <div class="row mb-3">
            <div class="col-lg-6">
                <h4>Following</h4>
                <p>Users Followed by {{ user.username }}</p>
            </div>
            <div class="col-lg-6 text-end">
                <a href="{{ url_for('main.followers', username=user.username) }}" class="btn btn-light">
                    <i class="fa fa-users"></i> Followers
                </a>
                <div id="export_buttons" class="mt-2"></div>
            </div>
        </div>
        {% endif %}
        <div class="row">
            <div class="col-lg-12">
                <table id="datatable" class="table table-bordered table-hover" style="width:100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>User</th>
                            <th>Since</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for follow in follows %}
                            {% if not follow.user == user %}
                            <tr>
                                <td>{{loop.index}}</td>
                                <td>
                                    <a href="{{ url_for('main.user_profile', username=follow.user.username) }}">
                                        <img src="{{ url_for('static', filename='dashboard/profile_pics/'+follow.user.image) }}" 
                                            alt="image.jpg" style="border-radius: 50%; height:40px; width:40px;">
                                        {{ follow.user.username }}
                                    </a>
                                </td>
                                <td>
                                    {{ moment(follow.date_followed).format('L') }}
                                </td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- end: DataTable -->
    </div>
</section>
{% endblock content %}

app/templates/main/user_profile.html
{% extends "main/layout/main_layout.html" %}
{% block content %}
<section class="profile-content">
    <div class="profile-image" style="background-image:url(/static/dashboard/header_images/{{user.header}})">
        <div class="profile-name">
            <h3>{{ user.username }}</h3>
        </div>
    </div>
    <div class="profile-bio">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            <div role="alert" class="alert alert-{{category}} alert-dismissible">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> </button>
                <strong><i class="fa fa-exclamation-circle"></i> 
                    {{ category|title }}!
                </strong> {{ message }}. 
            </div>
            {% endfor %}
        {% endif %}
        {% endwith %}
        <h3>{{ user.username }}'s Profile</h3>
        {% if user.job_title %}
        <span>
            {{ user.job_title }}
        </span>
        {% endif %}
        <br/>
        <p>
            {{ user.bio }}
        </p>
        <div class="m-t-5">
            <h4>Address</h4>
            <span>{{ user.address }}</span>
        </div>
        <div class="m-t-10">
            <h4>Blog Posts</h4>
            <a href="{{ url_for('main.user_posts', username=user.username) }}">
                <span class="badge bg-primary">{{ user.posts.count() }}</span>
                <span>Blog Post(s)</span>
            </a>
            
        </div>
        <div class="m-t-30">
            {% if current_user.can(Permission.FOLLOW) and user != current_user %}
                {% if not current_user.is_following(user) %}
                <a href="{{ url_for('main.follow', username=user.username) }}" 
                    class="btn btn-rounded btn-outline">FOLLOW</a>
                {% else %}
                <a href="{{ url_for('main.unfollow', username=user.username) }}" 
                    class="btn btn-rounded btn-outline">UNFOLLOW</a>
                {% endif %}
            {% endif %}
            <a href="{{ url_for('main.followers', username=user.username) }}">
                <span class="text-dark">FOLLOWERS:</span> 
                <span class="badge badge-pill bg-warning">{{ user.followers.count() - 1 }}</span>
            </a>
            <a href="{{ url_for('main.following', username=user.username) }}">
                <span class="text-dark">FOLLOWING:</span> 
                <span class="badge badge-pill bg-light">{{ user.followed.count() - 1 }}</span>
            </a>
            {% if current_user.is_authenticated and user != current_user and 
                user.is_following(current_user) %}
            <span class="badge bg-success">Follows you</span>
            {% endif %}
        </div>
        <div class="m-t-60">
            <h4>Skills</h4>
            <div class="p-progress-bar-container title-up small extra-small color">
                <div class="p-progress-bar" data-percent="100" data-delay="100" data-type="%">
                    <div class="progress-title">HTML5</div>
                </div>
            </div>
            <div class="p-progress-bar-container title-up small extra-small color">
                <div class="p-progress-bar" data-percent="94" data-delay="200" data-type="%">
                    <div class="progress-title">CSS3</div>
                </div>
            </div>
            <div class="p-progress-bar-container title-up small extra-small color">
                <div class="p-progress-bar" data-percent="78" data-delay="300" data-type="%">
                    <div class="progress-title">JQUERY</div>
                </div>
            </div>
            <div class="p-progress-bar-container title-up small extra-small color">
                <div class="p-progress-bar" data-percent="65" data-delay="400" data-type="%">
                    <div class="progress-title">MYSQL</div>
                </div>
            </div>
        </div>
        <hr class="space">
        <div class="profile-bio-footer">
            <div class="text-center"> &copy; 2021 POLO - Responsive Multi-Purpose HTML5 Template. All Rights
                Reserved.INSPIRO</div>
        </div>
    </div>
</section>
{% endblock content %}